# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(max_length=256, verbose_name='Category')),
                ('acti', models.BooleanField(max_length=3, verbose_name='ActivE')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=128, verbose_name='alt')),
                ('text', models.TextField(blank=True, max_length=512, verbose_name='text')),
                ('src', models.FileField(upload_to='image/%Y/%m/%d/')),
                ('acti', models.BooleanField(max_length=3, verbose_name='active')),
                ('small', models.CharField(max_length=256, verbose_name='small')),
                ('reg', models.DateTimeField(auto_now=True, max_length=256, verbose_name='Record')),
                ('cou', models.IntegerField(blank=True, default='0', verbose_name='Count')),
                ('cate', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='gallery.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cou', models.IntegerField(blank=True, verbose_name='Count')),
                ('reg', models.DateTimeField(auto_now=True, max_length=256, verbose_name='Record')),
                ('gal', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery')),
            ],
        ),
    ]
