# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20171128_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='counter',
        ),
        migrations.AddField(
            model_name='gallery',
            name='counterdown',
            field=models.IntegerField(blank=True, default='0', verbose_name='Count Down'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='counterup',
            field=models.IntegerField(blank=True, default='0', verbose_name='Count Up'),
        ),
    ]
